#!/usr/bin/env php
<?php
/* Author : Romain "Artefact2" Dalmaso <artefact2@gmail.com>
 * This program is free software. It comes without any warranty, to
 * the extent permitted by applicable law. You can redistribute it
 * and/or modify it under the terms of the Do What The Fuck You Want
 * To Public License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

require __DIR__.'/lib/inc.main.php';

// Try to fix blocks who have no inputs, yet more than 1 transaction
$req = "
SELECT hash
FROM blocks, number
JOIN blocks_num_transactions ON blocks_num_transactions.block = blocks.hash
LEFT JOIN blocks_num_inputs ON blocks_num_inputs.block = blocks.hash
WHERE num_inputs IS NULL 
AND num_transactions > 1
";

$req = pg_query($req);
while($r = pg_fetch_row($req)) {
	if(isset($hex)) echo "\n";
	$hex = bits2hex($r[0]);
	echo "fixing inputs for $hex...";

	$json = json_decode(shell_exec('bitcoind getblockbyhash '.$hex), true);
	insertBlock($r[1], $json, true);
}

if(isset($hex)) echo "\n";
