#!/usr/bin/env php
<?php
/* Author : Romain "Artefact2" Dalmaso <artefact2@gmail.com>
 * This program is free software. It comes without any warranty, to
 * the extent permitted by applicable law. You can redistribute it
 * and/or modify it under the terms of the Do What The Fuck You Want
 * To Public License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

require __DIR__.'/lib/inc.main.php';

@unlink('cookies.txt');

foreach($foundBy as $pool => $callback) {
	$in = call_user_func($callback);
	if(count($in) == 0) continue;

	$in = array_map(function($h) { return "B'".hex2bits($h)."'"; }, $in);
	$in = implode(',', $in);

	pg_query("UPDATE blocks SET found_by = '$pool' WHERE hash IN ($in) AND found_by IS NULL");
}
